// This file is auto-generated by Supabase CLI.
// Run: npx supabase gen types typescript --project-id tyeutrjziqzarzhxqwtz > src/types/database.ts
// It is currently maintained manually to keep query typing aligned with the app schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          organization: string | null;
          designation: string | null;
          bio: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          short_description: string | null;
          start_date: string;
          end_date: string;
          venue_name: string | null;
          venue_address: string | null;
          city: string | null;
          banner_image_url: string | null;
          thumbnail_image_url: string | null;
          max_capacity: number | null;
          registration_end_date: string | null;
          registration_open: boolean;
          is_featured: boolean;
          status: Database['public']['Enums']['event_status'];
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['events']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['events']['Insert']>;
        Relationships: [];
      };
      registrations: {
        Row: {
          id: string;
          event_id: string;
          user_id: string;
          category: Database['public']['Enums']['registration_category'];
          status: Database['public']['Enums']['registration_status'];
          dietary_needs: string | null;
          special_requirements: string | null;
          submission_data: Json | null;
          reference_number: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          submitted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['registrations']['Row'], 'id' | 'created_at' | 'updated_at' | 'submitted_at' | 'reference_number'>;
        Update: Partial<Database['public']['Tables']['registrations']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'registrations_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      approval_logs: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          action: Database['public']['Enums']['audit_action'];
          previous_status: string | null;
          new_status: string | null;
          performed_by: string;
          notes: string | null;
          metadata: Json | null;
          performed_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['approval_logs']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['approval_logs']['Insert']>;
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          event_id: string;
          title: string;
          description: string | null;
          session_type: Database['public']['Enums']['session_type'];
          session_date: string;
          start_time: string;
          end_time: string;
          room: string | null;
          max_seats: number | null;
          is_featured: boolean;
          track: string | null;
          tags: Json | null;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['sessions']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['sessions']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'sessions_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      qr_codes: {
        Row: {
          id: string;
          registration_id: string;
          qr_data: string;
          qr_image_url: string | null;
          validation_hash: string;
          is_active: boolean;
          generated_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['qr_codes']['Row'], 'id' | 'created_at' | 'generated_at'>;
        Update: Partial<Database['public']['Tables']['qr_codes']['Insert']>;
        Relationships: [];
      };
      check_in_logs: {
        Row: {
          id: string;
          registration_id: string;
          checked_in_by: string | null;
          qr_code_id: string | null;
          checked_in_at: string;
          checkin_method: Database['public']['Enums']['checkin_method'];
          location: string | null;
          device_info: string | null;
          notes: string | null;
          is_valid: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['check_in_logs']['Row'], 'id' | 'created_at' | 'checked_in_at'>;
        Update: Partial<Database['public']['Tables']['check_in_logs']['Insert']>;
        Relationships: [];
      };
      speakers: {
        Row: {
          id: string;
          event_id: string | null;
          full_name: string;
          email: string;
          bio: string | null;
          short_bio: string | null;
          designation: string | null;
          organization: string | null;
          photo_url: string | null;
          speaker_type: string | null;
          social_links: Json | null;
          slug: string;
          is_active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['speakers']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['speakers']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'speakers_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
        ];
      };
      roles: {
        Row: {
          id: string;
          name: Database['public']['Enums']['system_role'];
          description: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['roles']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['roles']['Insert']>;
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role_id: string;
          assigned_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['user_roles']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['user_roles']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'user_roles_role_id_fkey';
            columns: ['role_id'];
            isOneToOne: false;
            referencedRelation: 'roles';
            referencedColumns: ['id'];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: Database['public']['Enums']['audit_action'];
          entity_type: string;
          entity_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>;
        Relationships: [];
      };
      site_settings: {
        Row: {
          id: string;
          key: string;
          value: string;
          category: string;
          description: string | null;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['site_settings']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['site_settings']['Insert']>;
        Relationships: [];
      };
      cms_pages: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: Json;
          status: Database['public']['Enums']['content_status'];
          parent_id: string | null;
          seo_title: string | null;
          seo_description: string | null;
          canonical_url: string | null;
          metadata: Json | null;
          author_id: string | null;
          display_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['cms_pages']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['cms_pages']['Insert']>;
        Relationships: [];
      };
      blog_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['blog_categories']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['blog_categories']['Insert']>;
        Relationships: [];
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string;
          content_json: Json | null;
          excerpt: string | null;
          featured_image_url: string | null;
          status: Database['public']['Enums']['content_status'];
          category_id: string | null;
          is_featured: boolean;
          seo_title: string | null;
          seo_description: string | null;
          tags: Json | null;
          reading_time_minutes: number | null;
          view_count: number;
          canonical_url: string | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['blog_posts']['Row'], 'id' | 'created_at' | 'updated_at' | 'view_count'>;
        Update: Partial<Database['public']['Tables']['blog_posts']['Insert']>;
        Relationships: [];
      };
      media_assets: {
        Row: {
          id: string;
          filename: string;
          original_filename: string;
          file_url: string;
          file_size: number;
          mime_type: string;
          media_type: Database['public']['Enums']['media_type'];
          alt_text: string | null;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['media_assets']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['media_assets']['Insert']>;
        Relationships: [];
      };
      faq_items: {
        Row: {
          id: string;
          question: string;
          answer: string;
          category: string;
          sort_order: number;
          is_active: boolean;
          event_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['faq_items']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['faq_items']['Insert']>;
        Relationships: [];
      };
      email_templates: {
        Row: {
          id: string;
          name: string;
          slug: string;
          subject: string;
          html_content: string;
          text_content: string | null;
          variables: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['email_templates']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['email_templates']['Insert']>;
        Relationships: [];
      };
      email_logs: {
        Row: {
          id: string;
          template_id: string | null;
          registration_id: string | null;
          recipient_email: string;
          subject: string;
          status: Database['public']['Enums']['email_status'];
          error_message: string | null;
          provider_message_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['email_logs']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['email_logs']['Insert']>;
        Relationships: [];
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          organization: string | null;
          subject: string;
          message: string;
          status: string;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['contact_submissions']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['contact_submissions']['Insert']>;
        Relationships: [];
      };
      newsletter_subscribers: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          is_active: boolean;
          subscribed_at: string | null;
          unsubscribed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['newsletter_subscribers']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['newsletter_subscribers']['Insert']>;
        Relationships: [];
      };
      partners: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          website_url: string | null;
          tier: Database['public']['Enums']['partner_tier'] | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['partners']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['partners']['Insert']>;
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {
      event_status: 'draft' | 'published' | 'archived' | 'cancelled';
      registration_status: 'pending' | 'under_review' | 'approved' | 'rejected' | 'waitlisted' | 'checked_in' | 'cancelled';
      application_status: 'submitted' | 'under_review' | 'approved' | 'rejected' | 'waitlisted' | 'withdrawn';
      content_status: 'draft' | 'published' | 'archived';
      session_type: 'keynote' | 'panel' | 'workshop' | 'fireside_chat' | 'networking' | 'break' | 'ceremony';
      partner_tier: 'title' | 'platinum' | 'gold' | 'silver' | 'bronze' | 'media' | 'knowledge' | 'community';
      checkin_method: 'qr_scan' | 'manual_search' | 'manual_override';
      audit_action: 'create' | 'update' | 'delete' | 'approve' | 'reject' | 'waitlist' | 'checkin' | 'publish' | 'archive' | 'login' | 'role_assign' | 'role_revoke' | 'export' | 'bulk_action';
      media_type: 'image' | 'document' | 'video' | 'other';
      registration_category: 'delegate' | 'vip' | 'corporate' | 'government' | 'ngo' | 'academic' | 'media' | 'student' | 'speaker' | 'volunteer' | 'other';
      email_status: 'queued' | 'sent' | 'delivered' | 'failed' | 'bounced';
      system_role: 'super_admin' | 'event_admin' | 'content_admin' | 'reviewer' | 'checkin_staff' | 'registered_user';
    };
  };
}
